name: Build

on: [push]

jobs:
  framework:
    name: .NET Framework
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: NuGet packages
      working-directory: .
      run: nuget restore rocket_engine_calc.sln
      
    - name: MSBuild MLRuntime Release
      working-directory: ./rocket_engine_calc/MlRuntime
      run: msbuild MLRuntime.csproj -p:Configuration=Release

    - name: MSBuild rocket_engine_calc Release
      working-directory: ./rocket_engine_calc
      run: msbuild rocket_engine_calc.csproj -p:Configuration=Release
      
  core:
    name: .NET Core
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@master
        
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 3.0.100
          
      - run: dotnet build ./rocket_engine_calc_core/rocket_engine_calc_core.csproj
