name: .NET Framework

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild MLRuntime Release
      working-directory: ./rocket_engine_calc/MlRuntime
      run: msbuild MLRuntime.csproj -p:Configuration=Release

    - name: MSBuild rocket_engine_calc Release
      working-directory: ./rocket_engine_calc
      run: msbuild rocket_engine_calc.csproj -p:Configuration=Release
